In [1]:
import numpy as np
import pickle
import torch

In [2]:
def take_per_row(A, indx, num_elem):
    all_indx = indx[:,None] + np.arange(num_elem)
    return A[torch.arange(all_indx.shape[0])[:,None], all_indx]

In [3]:
A = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

In [8]:
indx = [1, 0, 2]
num_elem = 2

In [12]:
take_per_row(torch.tensor(A), torch.tensor(indx), num_elem)

tensor([[ 2,  3],
        [ 5,  6],
        [11, 12]])

In [14]:
print(torch.tensor(indx)[:,None])

tensor([[1],
        [0],
        [2]])


In [15]:
print(np.arange(num_elem))

[0 1]


In [13]:
all_indx = torch.tensor(indx)[:,None] + np.arange(num_elem)
print(all_indx)

tensor([[1, 2],
        [0, 1],
        [2, 3]])


In [17]:
torch.tensor(A)[torch.arange(all_indx.shape[0])[:,None], all_indx]

tensor([[ 2,  3],
        [ 5,  6],
        [11, 12]])

In [ ]:
crop_l = np.random.randint(low=2 ** (self.temporal_unit + 1), high=ts_l+1)
crop_left = np.random.randint(ts_l - crop_l + 1)
crop_right = crop_left + crop_l
crop_eleft = np.random.randint(crop_left + 1)
crop_eright = np.random.randint(low=crop_right, high=ts_l + 1)
crop_offset = np.random.randint(low=-crop_eleft, high=ts_l - crop_eright + 1, size=x.size(0))
take_per_row(x, crop_offset + crop_eleft, crop_right - crop_eleft)

In [11]:
np.random.randint(10)

3

In [24]:
import torch
import torch.nn as nn

# 入力データのサイズ
input_size = (3, 275, 10)

# ダミーの入力データを生成
input_data = torch.randn(input_size)

# 畳み込み層を定義
conv1d = nn.Conv1d(in_channels=input_size[1], out_channels=input_size[1]-5+1, kernel_size=5, padding=1)

# 畳み込み演算を適用
output = conv1d(input_data)  # チャンネル次元と長さ次元を入れ替えてから畳み込み演算を適用

# 出力のサイズを確認
print("畳み込み後の出力サイズ:", output.size())

畳み込み後の出力サイズ: torch.Size([3, 271, 8])


In [28]:
data = [
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5]
]

# 分割するデータの形式
formats = [
    [1, 2],
    [2, 3],
    [3, 4]
]

# 分割したデータを格納するリスト
split_data = []

for format in formats:
    start_index, end_index = format  # データ形式から開始インデックスと終了インデックスを取得
    split = []
    for row in data:
        # 開始インデックスと終了インデックスがデータの範囲内に収まるかを確認してからデータを抽出
        if start_index <= len(row) and end_index <= len(row):
            split.append(row[start_index - 1:end_index])
        else:
            print("データ形式がデータの範囲外です。")
    split_data.append(split)

print(split_data[0])


[[1, 2], [1, 2], [1, 2], [1, 2], [1, 2]]


In [29]:
import numpy as np

# 入力データの形状
data_shape = (3, 20, 10)

# スライディングウィンドウの幅
window_size = 5

# 入力データの作成 (仮のデータ)
data = np.random.rand(*data_shape)

# 分割したデータを格納するリスト
split_data = []

# スライディングウィンドウで2次元目を分割
for i in range(data_shape[1] - window_size + 1):
    split = data[:, i:i+window_size, :]
    split_data.append(split)

# 分割されたデータの表示
for i, split in enumerate(split_data):
    print(f"分割{i+1}:", split.shape)

分割1: (3, 5, 10)
分割2: (3, 5, 10)
分割3: (3, 5, 10)
分割4: (3, 5, 10)
分割5: (3, 5, 10)
分割6: (3, 5, 10)
分割7: (3, 5, 10)
分割8: (3, 5, 10)
分割9: (3, 5, 10)
分割10: (3, 5, 10)
分割11: (3, 5, 10)
分割12: (3, 5, 10)
分割13: (3, 5, 10)
分割14: (3, 5, 10)
分割15: (3, 5, 10)
分割16: (3, 5, 10)


In [30]:
# 分割されたデータを結合する
combined_data = np.concatenate(split_data, axis=1)

# 結合されたデータの形状を表示
print("結合されたデータの形状:", combined_data.shape)

結合されたデータの形状: (3, 80, 10)
